"""adiciona data previsao em uma conta

Revision ID: 4916ace23ee6
Revises: fd88572f7852
Create Date: 2024-09-19 17:08:21.078459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4916ace23ee6'
down_revision = 'fd88572f7852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_contas', sa.Column('data_previsao', sa.DateTime(), nullable=True))
    
    op.execute('UPDATE tbl_contas SET data_previsao = now()')
    op.alter_column('tbl_contas', 'data_previsao', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_contas', 'data_previsao')
    # ### end Alembic commands ###
