"""Cria tabela fornecedor cliente

Revision ID: 658866251765
Revises: 
Create Date: 2024-09-10 16:50:25.070389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658866251765'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_contas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('desc', sa.String(length=30), nullable=True),
    sa.Column('valor', sa.Numeric(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_fornecedor_cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_fornecedor_cliente')
    op.drop_table('tbl_contas')
    # ### end Alembic commands ###
