"""altera datetime para date

Revision ID: 9ecbc04c9e3f
Revises: 4916ace23ee6
Create Date: 2024-09-19 17:28:14.322539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecbc04c9e3f'
down_revision = '4916ace23ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE tbl_contas ALTER COLUMN data_baixa TYPE date')
    op.execute('ALTER TABLE tbl_contas ALTER COLUMN data_previsao TYPE date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE tbl_contas ALTER COLUMN data_baixa TYPE timestamp')
    op.execute('ALTER TABLE tbl_contas ALTER COLUMN data_previsao TYPE timestamp')
    # ### end Alembic commands ###
