"""Cria tabela de cria contas a pagar e receber

Revision ID: fa1bed20258d
Revises: 
Create Date: 2024-09-05 12:12:31.858452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1bed20258d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_contas',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('desc', sa.String(length=30), nullable=True),
        sa.Column('valor', sa.Numeric(), nullable=True),
        sa.Column('tipo', sa.String(length=30), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_contas')
    # ### end Alembic commands ###
