"""adiciona colunas de baixa de uma conta

Revision ID: fd88572f7852
Revises: 28b57a6600a3
Create Date: 2024-09-17 16:24:06.393462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd88572f7852'
down_revision = '28b57a6600a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_contas', sa.Column('data_baixa', sa.DateTime(), nullable=True))
    op.add_column('tbl_contas', sa.Column('valor_baixa', sa.Numeric(), nullable=True))
    op.add_column('tbl_contas', sa.Column('esta_baixada', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_contas', 'esta_baixada')
    op.drop_column('tbl_contas', 'valor_baixa')
    op.drop_column('tbl_contas', 'data_baixa')
    # ### end Alembic commands ###
